#!/usr/bin/env python3
"""Merge params.json + basin centroids into src/data/modelParams.ts."""

import json
from pathlib import Path

from fetch_training_data import STATIONS

HERE = Path(__file__).parent
params = json.loads((HERE / "params.json").read_text())

# only ship models with real validation skill; the UI also shows this number
MIN_SKILL = 0.45

# stations where the hindcast showed persistence beats the model — dam-
# controlled flow that rainfall cannot predict (see hindcast_report.json)
EXCLUDE = {
    "02GA016": "Shand Dam release: persistence beats the model",
    "02HF002": "Gull dam release: no rainfall signal",
}

entries = {}
for st, rec in sorted(params.items()):
    skill = rec["fit"]["val_sqrt_nse"]
    keep = skill >= MIN_SKILL and st not in EXCLUDE
    why = EXCLUDE.get(st, f"val sqrt-NSE {skill:+.3f}")
    print(f"{st}: {why} {'SHIP' if keep else 'skip'}")
    if keep:
        entries[st] = {
            "area_km2": rec["area_km2"],
            "centroid": list(STATIONS[st]),
            "params": rec["params"],
            "fit": rec["fit"],
        }

out = HERE.parent / "src" / "data" / "modelParams.ts"
body = json.dumps(entries, indent=2)
out.write_text(
    "// GENERATED by model/export_params.py — do not edit by hand.\n"
    "// Bucket-model parameters calibrated on WSC daily flows + ERA5 weather.\n"
    "// fit.val_sqrt_nse is NSE on sqrt(flows) over the 2016+ holdout.\n\n"
    "export interface ModelEntry {\n"
    "  area_km2: number\n"
    "  centroid: [number, number]\n"
    "  params: {\n"
    "    smax: number; beta: number; ddf: number; tmelt: number\n"
    "    alpha: number; kq: number; ks: number; kr: number\n"
    "  }\n"
    "  fit: { val_sqrt_nse: number; val_nse: number; train_sqrt_nse: number;\n"
    "         train_nse: number; n_train: number; n_val: number }\n"
    "}\n\n"
    f"export const modelParams: Record<string, ModelEntry> = {body}\n"
)
print(f"wrote {out} with {len(entries)} models")
