// GENERATED by model/export_params.py — do not edit by hand.
// Bucket-model parameters calibrated on WSC daily flows + ERA5 weather.
// fit.val_sqrt_nse is NSE on sqrt(flows) over the 2016+ holdout.

export interface ModelEntry {
  area_km2: number
  centroid: [number, number]
  params: {
    smax: number; beta: number; ddf: number; tmelt: number
    alpha: number; kq: number; ks: number; kr: number
  }
  fit: { val_sqrt_nse: number; val_nse: number; train_sqrt_nse: number;
         train_nse: number; n_train: number; n_val: number }
}

export const modelParams: Record<string, ModelEntry> = {}
